### PR TITLE
Feature rfuqr

### PR DESCRIPTION
**Pull request by jaurentz**
This PR contains the square root free unitary QR code.

### CODE REVIEW

**Comment by thomasmach** [comment]
I found some strange computation in benchmark_z_rfr3_turnover.f90. CC and SS are compute normalized but then overwritten with the next random number generation. I think you should review my changes.

I believe the function src/complex_double/q_urffact_singlestep_shift.f90 is also spurious now.

**Comment by jaurentz** [comment]
I just undid my bad changes and removed the spurious file. Sorry.

**Comment by thomasmach** [comment]
I reviewed some of the files, but I am not done with the review yet. I will probably only get to it on Saturday.

I have two more questions:
1) Did you try the symtrid with the new implementation?
2) Sometimes you use conjg(z)*z to compute the square of the absolute value and sometimes dble(z)**2 + aimag(z)**2. Which one is faster? And should we settle on one option?

**Comment by jaurentz** [comment]
1. Yes I did try and we are within half a digit of our old unitary code in the worst case, and on average essentially the same. 
2. I did a grep and can't find any such instance of conjg(z)*z. The conjg(z)*z wastes 4 flops and is susceptible to rounding error due to non commutativity of flops.

**Comment by thomasmach** [comment]
Great work.

**Pull request merged**
