### PR TITLE
Feature twisted upr1

### PR DESCRIPTION
**Pull request by jaurentz**
This pull request adds two new routines: z_upr1fact_rot3throughtri and z_upr1fact_2x2deflation; and cleans up the makefiles so that recursive make is called much less often.

### CODE REVIEW

**Comment by thomasmach** [comment]
When function __z_upr1fact_rot3throughtri__ is used, e.g., in __z_upr1fact_2x2deflation__ line 170, then the variables D and R are restricted to specific rows. I am concerned that this means that the whole row is copied to a new variable. This might slow down the algorithm significantly.

**Comment by jaurentz** [comment]
All routines in fortran are pass-by-pointer. At worst we are creating a new array of pointers but I don't think this is the case. A quick google search and no answers. 

My new worry is array access in a twisted QR call. In this case half of R and D are ignored but the ignored elements are interlaced with the desired elements. Maybe there should be D1, D2, R1 and R2 arrays?

**Comment by thomasmach** [comment]
I just correct two minor issues.

**Comment by thomasmach** [comment]
The idea of putting D and R together was to interlace the variables, because by chasing a bulge a round we need elements next to each other.

Does the pointer which is passed to the function contains the distance between the elements?
In Lapack the distance is provided by an additional integer. That might be redundant in modern Fortran, but i thought it's necessary.

**Comment by thomasmach** [comment]
Yes, it's a new issue. Most of the time you were following this convention, but I, indeed, didn't check if it's everywhere like this.

**Comment by jaurentz** [comment]
You can also add a stride in F90
```fortran
A(lower:upper[:stride])
```

**Comment by thomasmach** [comment]
Ok, my concern is discussed. I think we can merge this pull request.

**Pull request merged**
