### PR TITLE
Set core subroutines

### PR DESCRIPTION
**Pull request by jaurentz**
I have updated all the complex UQR code to use the new simplified 
core routines. I think this might be a good time to merge with development.
There is still a lot to do but if we wait any longer the PR will take days to 
review.

### CODE REVIEW

**Comment by thomasmach** [comment]
The paper mentions real double shift code. However, the pull request removes the functions d_orthfact_* from eiscor. Should we adapt the paper or put the functions back in eiscor?

**Comment by thomasmach** [comment]
The pull request also removes the test functions.

**Comment by jaurentz** [comment]
set-core-subroutines does not currently contain any of the doubleshift code. When I was writing this stuff I started with a clean slate and added in the updated routines one at a time. I just haven't gotten to the real code yet. This branch is essentially a complete overhaul of development. Maybe I should just keep editing in this branch and defer the merge until the doubleshift code is done as well? There is no rush to make this merge and the master branch is still untouched.

**Comment by thomasmach** [comment]
Ok, then I think we can merge it, and add the double code back later.

**Comment by jaurentz** [comment]
I guess out of all the files to look at, I am most concerned with the core routines:

d/z_rot*_*.f90

and 

z_uni*_*.f90

All the upr1fact code is still under development.

**Comment by thomasmach** [comment]
I checked the files you mentioned again. Let's pull it.

**Pull request merged**
