### PR TITLE
Set core subroutines

### PR DESCRIPTION
**Pull request by jaurentz**
I've finished updating the real unitary QR code to use the simplified framework. Currently the test for 
`d_rot2_turnover` fails on my laptop. I think this is related to the histogram issue for `z_rot3_turnover`. I'm not sure what you did in that case but I think it should be repeated here.

### CODE REVIEW

**Comment by jaurentz** [comment]
Sorry for so many lines again. We also should decide what to do about #54 before I start working on `feature-twisted-upr1` again.

**Comment by thomasmach** [comment]
I made the histogram test easier to pass. However, that the test wasn't passed actually indicates that the new turnover code isn't quite as good as the old one.

**Comment by jaurentz** [comment]
The test now passes on my machine. The reason for the discrepancy is that I'm using my laptop and not my desktop as I have done previously. It appears manufacturers are far from having a uniform floating point standard.

**Comment by thomasmach** [comment]
The test also didn't pass on my computer, and I was always using the same one (including the same compiler and everything).

**Comment by jaurentz** [comment]
Updated to be more accurate. There are a lot of details in this branch that need to be addressed, mostly related to documentation.

**Pull request merged**
