### PR TITLE
Feature twisted qz

### PR DESCRIPTION
**Pull request by thomasmach**
This is the pull request for the twisted QR and QZ upr1-code. I will review it first myself and then we need a second review to ensure the four-eyes policy.

### CODE REVIEW

**Comment by thomasmach** [comment]
What do we do with:
example_z_poly_2roots_norm and
example_z_poly_roots?

Are these examples too detailed? Can we keep them?

**Comment by jaurentz** [comment]
Those are way too detailed. IS z_poly_roots going to be included?

**Comment by thomasmach** [comment]
I think z_poly_roots should be included. I just had another look into z_poly_roots. At the moment z_poly_roots scales the polynomial and uses QZ. According to our latest analysis, this is only necessary if the norm is huge (>1e8...1e16). Thus there are maybe some more changes necessary.

**Comment by thomasmach** [comment]
I am done with my round of reviewing the pull request.
I have modified z_poly_roots to use the QR for smaller norms of the monic polynomial and adapted the example_z_poly_roots.

**Comment by jaurentz** [comment]
The example [example_z_different_patterns](https://github.com/eiscor/eiscor/blob/feature-twisted-qz/example/complex_double/example_z_different_patterns.f90) is unfinished.

**Pull request merged**
