### PR TITLE
Feature uqr examples

### PR DESCRIPTION
**Pull request by jaurentz**
This pull request is in preparation for the release of eiscor v0.2.0. The naming convention has already been updated and the core subroutines have been refactored.

### CODE REVIEW

**Comment by thomasmach** [comment]
The guide.md uses *Eiscor* and *eiscor* at the begin of the sentence. I trend towards using the latter one, but the main point is that the capitalization should be uniform.

**Comment by jaurentz** [comment]
I agree. I think we should go against traditional English grammar and use lower-case. Does this mean it should be __eiscor guide__?

**Comment by thomasmach** [comment]
Yes, it would mean that it's an __eiscor guide__.

**Comment by jaurentz** [comment]
Go for it.

**Comment by thomasmach** [comment]
I timed the z_rootsofunity for version 0.1.0 and for the version in this branch. The old version is 1.89s / 4096 eigenvalues and the new one is 2.24s / 4096 eigenvalues.
I pull this request anyway, but we need some more tuning before we can pull to master.

**Pull request merged**
